### ISSUE TITLE
gem c rails brings back a pre-release version of the gem

### ISSUE THREAD

**Issue by mikegehard** [BlueVajra/ruby_gem_workflow#1]
This is a sweet workflow!

gem 'rails', '~> 4.1.0.rc2' is what I get back and the README.md says it brings back latest non-prerelease version.

**Comment by mikegehard** [comment]
Downloaded  the latest and it works as advertised. Thanks!

**Comment by BlueVajra** [comment]
Thanks for testing it out... I will let you know when I make any updates.

I would also appreciate feedback on the README and any other information I
should be paying attention to for a publicly available script like this.
